version = 0.1

[default.deploy.parameters]
stack_name = "serverless-crud-app"
resolve_s3 = true
s3_prefix = "serverless-crud-app"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "JwtSecretArn=\"arn:aws:secretsmanager:us-east-1:639729144396:secret:serverless-crud-jwt-secret-Vzuvl6\""
disable_rollback = true

[default.global.parameters]
region = "us-east-1"
