name: 🚀 Deploy Serverless App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      JWT_SECRET_ARN: ${{ secrets.JWT_SECRET_ARN }}

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🏗️ Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: 🔐 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 🏗️ Build
        run: sam build

      - name: 🔍 Validate Secrets
        run: |
          if [ -z "$JWT_SECRET_ARN" ]; then
            echo "❌ JWT_SECRET_ARN is missing"
            exit 1
          fi

          if [[ "$JWT_SECRET_ARN" =~ ^arn: ]]; then
            echo "✅ Valid ARN detected"
          else
            echo "❌ Invalid ARN format"
            exit 1
          fi

      - name: 🚀 Deploy
        run: |
          sam deploy \
            --stack-name serverless-crud-app \
            --region $AWS_REGION \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --parameter-overrides JwtSecretArn=$JWT_SECRET_ARN
